version: '3'

services:

  loki:
    image: grafana/loki:latest
    container_name: loki
    restart: unless-stopped

  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 8443:443
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:rw
      - ./${SERVER_KEY}:/${SERVER_KEY}:ro
      - ./${SERVER_CERT}:/${SERVER_CERT}:ro
    environment:
      SERVER: ${SERVER}
      SERVER_KEY: ${SERVER_KEY}
      SERVER_CERT: ${SERVER_CERT}
      LOKI_USER: ${LOKI_USER}
      LOKI_PASSWORD: ${LOKI_PASSWORD}
